# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps: 
    #1. Checkout code
      - name: Checkout code
        uses: action/checkout@v3
    #2. Setup node.js
      - name: Setup node.js
        uses: action/setup-node@v3
    #3. Install dependencies
      - name: Install dependencies
        run: npm ci
    #4. Build
      - name: Build
        run: npm run build
    #5. Lint
      - name: Build
        run: npm run lint
    #6. Test
      - name: Build
        run: npm run lint
    #7. Fake deploy
      - name: Build
        run: echo "Deploy simulated, Build would be deployed here"
